# This Vagrantfile is meant as full GUI dev environment
# It still uses the "hashicorp/bionic box" because of compatibility
# issues with ubuntu-desktop and VirtualBox guest additions.

# Tested with VirtualBox 6.0.x and Vagrant 2.2.x

#
# PLUGINS
#
unless Vagrant.has_plugin?("vagrant-disksize")
  puts 'Installing vagrant-disksize Plugin...'
  system('vagrant plugin install vagrant-disksize')
end
unless Vagrant.has_plugin?("vagrant-vbguest")
  puts 'Installing vagrant-vbguest Plugin...'
  system('vagrant plugin install vagrant-vbguest')
end

#
# VAGRANT CONF
#
Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.define "visualBox"
  config.vm.hostname = "visualBox"
  config.disksize.size = '60GB'
  
  # Network and port configuration
  # Set ports as needed
  #config.vm.network :forwarded_port, guest: 8080, host: 8080

  # Set network
  # Private network
  # Configure host-only adapter in Host Network manager, VirtualBox before
  # You can specify an IP or remove it and let DCHP handle it
  #config.vm.network "private_network", ip: "192.*.*.*"

  # Bridged network
  # You can specify an IP or let DHCP handle it
  #config.vm.network "public_network"

  #
  # VIRTUALBOX CONF
  #
  config.vm.provider "virtualbox" do |v|
    v.name = "visualBox"
    v.gui = true
    v.check_guest_additions = true
    v.memory = 8192
    v.cpus = 4
    v.customize ["modifyvm", :id, "--vram", "128"]
    v.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    v.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
  end

  #
  # COMMAND LINE INSTRUCTIONS
  #
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    wget -O install.sh https://gitlab.com/f_PLT/dev-setup/-/raw/master/install.sh?inline=false
    chmod +x install.sh
    ./install.sh custom
    sudo apt-get update
    sudo apt-get -y upgrade
    echo
    sudo apt-get install -y ubuntu-desktop
    echo "Ubuntu-desktop has been installed and you should restart your VM."
    echo "Open your VM through Virtualbox the first time you open it (not with vagrant up)."
  SHELL
  
  config.vm.provision :shell, :inline => "sudo rm /etc/localtime && sudo ln -s /usr/share/zoneinfo/America/Montreal /etc/localtime", run: "always"
end
