# This is a baseline. Can be run as is, but it's expected you will set some parameters
# according to your host (like CPU's, memory and disk size), as well as customize
# the command-line parameters.
#
# The most common configuration options are documented and commented below.
# For a complete reference, please see the online documentation at
# https://docs.vagrantup.com.
# Every Vagrant development environment requires a box. You can search for
# boxes at https://vagrantcloud.com/search.

#
# BOX VARIABLES
#

# These are some (but not all) of the parameters you can change.
# They are grouped here for convinience.
VM_NAME = "vagrant-docker"

# Alternatively you can use "hashicorp/bionic64" instead as a base box.
# Hashicorp only recommends hashicorp and bento boxes.
VM_BOX = "bento/ubuntu-24.04"

# CPU and ram size can be changed now or later.
CPU_COUNT = 2
RAM_MB = 4096

PRIVATE_NET_IP = "192.168.56.103"

#
# VAGRANT CONFIGURATION
#
Vagrant.configure("2") do |config|
  config.vm.box = VM_BOX
  config.vm.define VM_NAME
  config.vm.hostname = VM_NAME
  #
  # Network and port configuration
  #
  # Set ports as needed
  #config.vm.network :forwarded_port, guest: 8080, host: 8080

  # Private network
  # Configure host-only adapter in Host Network manager, VirtualBox before
  # You can specify an IP or remove it and let DCHP handle it
  config.vm.network "private_network", ip: PRIVATE_NET_IP

  # Bridged network
  # You can specify an IP or let DHCP handle it
  #config.vm.network "public_network"

  # Share a folder between host and VM.
  # Can also be done later throught the GUI
  #config.vm.synced_folder "C:/projects"

  #
  # VIRTUALBOX CONFIGURATION
  #
  # For more options: https://www.virtualbox.org/manual/ch08.html#vboxmanage-cmd-overview
  config.vm.provider "virtualbox" do |vb|
    vb.name = VM_NAME
    vb.cpus = CPU_COUNT
    vb.memory = RAM_MB
	  vb.check_guest_additions = false
	  vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga" ]
    vb.customize ["modifyvm", :id, "--vram", "128"]
    vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    vb.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
    vb.customize ["modifyvm", :id, "--uartmode1", "disconnected" ]
    vb.customize ["modifyvm", :id, "--paravirtprovider", "kvm"]
    vb.customize ["modifyvm", :id, "--nestedpaging", "on"]
	  vb.customize ["modifyvm", :id, "--vrde", "off" ]
  end

  #
  # COMMAND LINE INSTRUCTIONS
  #
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    sudo apt-get update
    sudo apt-get install -y vim git curl tree build-essential

    # Install docker
    sudo apt-get install -y \
      ca-certificates \
      gnupg \
      lsb-release
    sudo mkdir -p /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg

    echo \
        "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
        $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    sudo apt-get update
    sudo chmod a+r /etc/apt/keyrings/docker.gpg
    sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
    sudo groupadd docker
    sudo usermod -aG docker $USER

  SHELL
  config.vm.provision :shell, :inline => "sudo rm /etc/localtime && sudo ln -s /usr/share/zoneinfo/America/Montreal /etc/localtime", run: "always"
end